### ISSUE TITLE
Map change time after mach

### ISSUE THREAD

**Issue by Marfeld** [abnerfs/cs2-rockthevote#25]
Could you add a time to "EndOfMapVote" in the config so that the map is not changed immediately when the mach is finished, but e.g. after 20 seconds. That you can still examine your statistics.

Greetings Mario

**Comment by abnerfs** [comment]
yeah seems like a good feature, I will add a cvar

**Comment by Marfeld** [comment]
Ohh, very nice, I'm glad :)
