### ISSUE TITLE
workshop_map

### ISSUE THREAD

**Issue by bigoth** [abnerfs/cs2-rockthevote#27]
hi,
 i try to edit the maplist.txt for workshop map. 
they are no exemple
 can you give an exemple plz

de_vertigo
cs_italy
de_inferno
cs_office
de_mirage
de_ancient
de_nuke
de_anubis
de_overpass
de_dust2

but for the workshop map ?   number map name ?

**Comment by olkkuzi** [comment]
Its uses same protocol for workshop maps.
Example:
//Put your map list here
awp_india
awp_lego_2
awp_ice

**Comment by bigoth** [comment]
i try workshop map ... but nothing

de_safehouse

official map works fine..
 any idea?

**Comment by olkkuzi** [comment]
I have all my maps in steam collection and then i have in my server launch options +host_workshop_collection <collection id>
and all workshop content is automatically dowloaded when i first time started server.

Then i have in my maplist.txt
awp_lego_2
awp_india
awp_ice

I use default folder for ws contet and is loccated same place than yours.
game/bin/win64/stemapps/workshop/contet/730

**Comment by bigoth** [comment]
for workshop_map  in the last update

de_safehouse:3070550406 

and now its work fine
https://github.com/abnerfs/cs2-rockthevote/releases/tag/v1.7.0

**Comment by abnerfs** [comment]
Yeah in the previous release you had to host the map your self before using it, with the latest one you just need the id
