### ISSUE TITLE
"TriggerRoundsBeforEnd" dont work

### ISSUE THREAD

**Issue by everkk** [abnerfs/cs2-rockthevote#34]
I have in config file "TriggerRoundsBeforEnd": 10 in "EndOfMapVote". but the voting still takes two rounds to complete the map. I have maxrounds 46. I using plugin on retake server.
```json
// This configuration was automatically generated by CounterStrikeSharp for plugin 'RockTheVote', at 2024/02/21 08:19:19
{
  "Version": 9,
  "Rtv": {
    "Enabled": true,
    "EnabledInWarmup": true,
    "NominationEnabled": true,
    "MinPlayers": 3,
    "MinRounds": 0,
    "ChangeMapImmediatly": true,
    "HideHudAfterVote": true,
    "MapsToShow": 6,
    "VoteDuration": 20,
    "VotePercentage": 60,
    "HudMenu": true
  },
  "Votemap": {
    "Enabled": false,
    "VotePercentage": 60,
    "ChangeMapImmediatly": true,
    "EnabledInWarmup": true,
    "MinPlayers": 0,
    "MinRounds": 0
  },
  "EndOfMapVote": {
    "Enabled": true,
    "MapsToShow": 6,
    "HudMenu": true,
    "ChangeMapImmediatly": false,
    "VoteDuration": 20,
    "HideHudAfterVote": true,
    "TriggerSecondsBeforeEnd": 250,
    "TriggerRoundsBeforEnd": 10
  },
  "Timeleft": {
    "ShowToAll": true
  },
  "Nextmap": {
    "ShowToAll": true
  }
}```

**Comment by lovasatt** [comment]
I tested the plugin, but the "EndOfMapVote" function not work properly in casual mode, since v170. ( not popping up the hud, and not changing map) The competitive mode was good!

**Comment by everkk** [comment]
> I tested the plugin, but the "EndOfMapVote" function not work properly in casual mode, since v170. ( not popping up the hud, and not changing map) The competitive mode was good!

yeah there is problem

**Comment by abnerfs** [comment]
I will be testing in casual mode and let you know about the fix

**Comment by abnerfs** [comment]
A few questions to help in the investigation:
- Is mp_halftime 1?
- Is mp_timelimit 0?

**Comment by everkk** [comment]
> A few questions to help in the investigation:
> 
> * Is mp_halftime 1?
> * Is mp_timelimit 0?

I use mp_timelimit 0

**Comment by everkk** [comment]
Still dont work. I using this plugin with retakes https://github.com/B3none/cs2-retakes

**Comment by abnerfs** [comment]
It should trigger the vote at round 36, when it is triggering?

**Comment by everkk** [comment]
> It should trigger the vote at round 36, when it is triggering?

Yeah in my config should be in 36 round. Now server crashing when i use !timeleft command.

**Comment by everkk** [comment]
Now vote not triggering completly

**Comment by abnerfs** [comment]
About the TriggerRoundsBeforeEnd try this new version that should consider the convar mp_match_can_clinch correctly in order to determine which round should trigger the vote https://github.com/abnerfs/cs2-rockthevote/releases/tag/v1.8.1
