### ISSUE TITLE
fr.json   traduction

### ISSUE THREAD

**Issue by bigoth** [abnerfs/cs2-rockthevote#37]
{
  "rtv.prefix": "{red}[RockTheVote]{default}",
  "votemap.prefix": "{red}[Votemap]{default}",
  "timeleft.prefix": "{red}[Timeleft]{default}",
  "timeleft.remaining-rounds": "{0} Manches restantes",
  "timeleft.remaining-time-hour": "Temps restant {0}:{1}:{2}",
  "timeleft.remaining-time-minute": "Temps restant {0} minute(s) et {1} seconde(s)",
  "timeleft.remaining-time-second": "Temps restant {0} seconde(s)",
  "timeleft.no-time-limit": "Il n'y a pas de limite de temps",
  "timeleft.last-round": "Ceci est la dernière manche",
  "timeleft.time-over": "Plus de temps, ceci est la dernière manche",
  "votemap.player-voted": "Le joueur {green}{0}{default} vote pour {green}{1}{default}",
  "votemap.already-voted": "Tu as déjà voté {green}{0}{default}",
  "votemap.in-the-map": "pour la carte {0}",
  "votemap.changing-map": "Changement de carte pour {green}{0}",
  "votemap.changing-map-next-round": "La carte sera changé {green}{0}{default} à la prochaine manche...",
  "general.votes-needed": "({0} voté, {1} nécessaire)",
  "general.invalid-map": "carte invalide",
  "nominate.nominated": "Le joueur {green}{0}{default} à nommé {green}{1}{default}, maintenant il y a {2} vote(s)",
  "nominate.already-nominated": "Tu as déjà nommé la carte {green}{0}{default}, elle a {1} vote(s)",
  "general.validation.current-map": "Tu ne peux pas choisir la carte actuelle",
  "general.validation.minimum-rounds": "Le nombre minimum de manche pour utiliser la commande est {0}",
  "general.validation.warmup": "Commande désactivée pendant l'échauffement.",
  "general.validation.minimum-players": "Le minimum de joueur requis pour utiliser la commande est {0}",
  "general.validation.disabled": "Commande désactivée pour l'instant",
  "rtv.rocked-the-vote": "Le joueur {green}{0}{default} veux un Rock the vote",
  "rtv.already-rocked-the-vote": "Tu as déjà lancé un Roke the vote",
  "rtv.votes-reached": "Nombre de vote requis, démarrage du vote...",
  "rtv.disabled": "Rtv est désactivé",
  "emv.you-voted": "Tu as voté pour {0}",
  "emv.vote-ended": "Vote terminé la prochaine carte sera {green}{0}{default} ({1:N2}% of {2} vote(s))",
  "emv.vote-ended-no-votes": "pas de vote, la prochaine carte sera {green}{0}",
  "general.changing-map": "Changement de carte pour {green}{0}",
  "general.changing-map-next-round": "La carte va être changé pour {green}{0}{default} au prochain tour...",
  "emv.hud.menu-title": "Voter pour la prochaine carte:",
  "emv.hud.hud-timer": "Voter pour la prochaine carte: {0}s",
  "emv.hud.finished": "Vote terminé, prochaine carte: {0}",
  "nextmap": "La prochaine carte sera {green}{0}",
  "nextmap.decided-by-vote": "La nouvelle carte sera décidé par vote"
}

**Comment by crashzk** [comment]
Implemented in the latest version https://github.com/abnerfs/cs2-rockthevote/releases/tag/v1.7.4
