### ISSUE TITLE
[Enhancement]: Simplify with "WS:" Instead of Workshop IDs

### ISSUE THREAD

**Issue by criskkky** [abnerfs/cs2-rockthevote#40]
Adding workshop IDs individually might be inefficient. Why not simplify it by using "ws:" similar to <https://github.com/justinnobledev/cs2-mapchooser>? 😄

**Comment by criskkky** [comment]
> might be inefficient

Specially If you have too many maps

**Comment by Ryuujin555** [comment]
It was on ws before but sometimes server could not find ws map even tho it was running with collection and it was even worse when you had few maps de_cbble, now with :ID added not only you can rename map but it find without problem - It is awesome and prob best plugin to change maps out here.

**Comment by criskkky** [comment]
What about allow both ways 👀, for me at least didn't had problems with "WS"

**Comment by abnerfs** [comment]
The plugin already work both ways:
- If you are hosting the ws map yourself (by using a collection for instance) you just need to put the map name and it will work (without any ws: prefix)
- Otherwise you put the name + :ID
