### ISSUE TITLE
[REQ] `HudMenu` option in `!votemap` command

### ISSUE THREAD

**Issue by crashzk** [abnerfs/cs2-rockthevote#41]
https://github.com/abnerfs/cs2-rockthevote/blob/da9d230afc0eb643eb9dfb77e0273e804de68f41/Config.cs#L55-L63

I believe the option to activate voting via **HudMenu** in the `!votemap` command would be interesting.

**Comment by abnerfs** [comment]
Added in https://github.com/abnerfs/cs2-rockthevote/releases/tag/v1.8.0
