### ISSUE TITLE
!timeleft crashing server

### ISSUE THREAD

**Issue by everkk** [abnerfs/cs2-rockthevote#42]
!timeleft instat crashing server

**Comment by abnerfs** [comment]
Can you post any log that could help in the investigation?

**Comment by abnerfs** [comment]
Also which version are you using?

**Comment by everkk** [comment]
After update to newest version all works great. Thanks a lot.

**Comment by everkk** [comment]
After update to 1.8.3 trigger end vote map works perfect.
