### ISSUE TITLE
Only 4 maps in vote

### ISSUE THREAD

**Issue by everkk** [abnerfs/cs2-rockthevote#46]
Hello i have "MapsToShow": 6, in my cfg file but in vote shows only 4.

**Comment by everkk** [comment]
This is crazy now in vote is normal 6 map idk why

**Comment by abnerfs** [comment]
Let me know if it happens again, it is weird

**Comment by everkk** [comment]
Its random sometimes 6 maps in vote sometimes 4, 5

**Comment by aronmgv** [comment]
I confirm, I have `MapsToShow: 9` but server is showing only 6.. restarted multiple times..
