### ISSUE TITLE
Only 4 maps in vote

### ISSUE THREAD

**Issue by everkk** [abnerfs/cs2-rockthevote#47]
I tested this and its random. Sometimes i have normal 6 maps in vote, sometimes 4, 5.

**Comment by mayersgamer** [comment]
how many maps did you add in map list ? an how many did you exclude that already been played

**Comment by everkk** [comment]
> how many maps did you add in map list ? an how many did you exclude that already been played

![image](https://github.com/abnerfs/cs2-rockthevote/assets/67241375/27cc5649-7a45-4b04-a8df-65cd5839a34e)

**Comment by everkk** [comment]
You can chech this on my server 137.74.7.15:30087 if you want

**Comment by mayersgamer** [comment]
its working fine with me after testing for 3 days

**Comment by everkk** [comment]
> its working fine with me after testing for 3 days

I tested this with two maps more added in maplist.txt and now working. I thinking problem is there. If i have only 8 maps works bad, when i have 10 maps work great.

**Comment by mayersgamer** [comment]
ok you can close this issue
