### ISSUE TITLE
The crashes are happening unexpectedly

### ISSUE THREAD

**Issue by NikolaJyun** [abnerfs/cs2-rockthevote#69]
Every time the server crashes and I check the logs, I see these two types of crashes. It usually occurs when changing maps.

cs2_rockthevote.NominationCommand.PlayerDisconnected(CCSPlayerController player) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Features/NominationCommand.cs:line 177[39;49m

cs2_rockthevote.Plugin.EventPlayerDisconnectVotemap(EventPlayerDisconnect event, GameEventInfo eventInfo) in /home/runner/work/cs2-rockthevote/cs2-rockthevote/Features/VotemapCommand.cs:line 25[39;49m

**Comment by ZeroCPU** [comment]
Me too
